services:
  - type: web
    name: isrel-portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
