# Generated by Django 6.1.1 on 2026-09-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='SRM Institute of Science and Technology (SRMIST)', max_length=200)),
                ('degree', models.CharField(default='B.Tech in Computer Science', max_length=150)),
                ('specialization', models.CharField(default='Data Science specialization', max_length=150)),
                ('graduation_date', models.CharField(default='Expected Graduation: May 2029', max_length=100)),
                ('description', models.TextField(blank=True, default='Focusing on core computer science foundations, algorithms, machine learning, data engineering, and modern web architectures.')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ISREL', max_length=100)),
                ('title', models.CharField(default='Aspiring Web Developer & Data Science Enthusiast', max_length=200)),
                ('summary', models.TextField(default='Passionate Web Developer and Data Science Enthusiast currently pursuing a B.Tech in Computer Science (Data Science specialization) at SRM University. Skilled in Python, Front-End Development, and Data Analysis. Dedicated to building user-friendly, data-driven solutions.')),
                ('career_objective', models.TextField(default='To grow as a Web Developer & Data Scientist, contributing to innovative projects that combine creativity, data, and technology while continuously learning in a dynamic environment.')),
                ('location', models.CharField(default='Chennai, Tamil Nadu, India', max_length=150)),
                ('email', models.EmailField(default='makportx@gmail.com', max_length=254)),
                ('linkedin', models.URLField(default='https://linkedin.com/in/isrel')),
                ('github', models.URLField(default='https://github.com/isrel')),
                ('available_for_opportunities', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('ai_ml', 'AI & Machine Learning'), ('fullstack', 'Web Development & Full Stack'), ('data_science', 'Data Science & Dashboards')], default='fullstack', max_length=30)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('extended_details', models.TextField(blank=True, help_text='Detailed project breakdown, challenges, solutions, and impact.')),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies, e.g. Python, OpenCV, Tkinter', max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=True)),
                ('icon_name', models.CharField(default='folder', help_text='Lucide icon name', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('programming', 'Programming'), ('data_science', 'Data Science & AI'), ('tools', 'Tools & Workflow')], default='web', max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('level_note', models.CharField(blank=True, help_text="e.g., 'Proficient', 'Intermediate', 'basics'", max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=85, help_text='Percentage 0-100 for visual bar')),
                ('icon_name', models.CharField(default='code', help_text='Lucide icon name', max_length=50)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='check-circle-2', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
